// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorApp2.Models;

public partial class Comprobante
{
    public string NcF { get; set; }

    public string Rnc { get; set; }

    public decimal Monto { get; set; }

    public string Itbis { get; set; }

    public int EstadoId { get; set; }

    public DateTime FechaRegistro { get; set; }

    public virtual Estado Estado { get; set; }
}