// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BlazorApp2.Models;

public partial class DBADGIIContext : DbContext
{
    public DBADGIIContext(DbContextOptions<DBADGIIContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Comprobante> Comprobantes { get; set; }

    public virtual DbSet<Contribuyente> Contribuyentes { get; set; }

    public virtual DbSet<Estado> Estados { get; set; }

    public virtual DbSet<Tipo> Tipos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Comprobante>(entity =>
        {
            entity.HasKey(e => e.NcF);

            entity.ToTable("Comprobante");

            entity.Property(e => e.NcF)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.EstadoId).HasColumnName("Estado ID");
            entity.Property(e => e.FechaRegistro).HasColumnType("datetime");
            entity.Property(e => e.Itbis)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Monto).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Rnc)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Estado).WithMany(p => p.Comprobantes)
                .HasForeignKey(d => d.EstadoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Comprobante_Estado");
        });

        modelBuilder.Entity<Contribuyente>(entity =>
        {
            entity.HasKey(e => e.RncCedula).HasName("PK__dgiicont__D95DA7533E81B266");

            entity.ToTable("contribuyentes");

            entity.Property(e => e.RncCedula)
                .HasMaxLength(13)
                .IsUnicode(false)
                .HasColumnName("RNC_cedula");
            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.FechaRegistro)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("Fecha_registro");
            entity.Property(e => e.RazonSocial)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Razon_social");
            entity.Property(e => e.TipoId).HasColumnName("Tipo ID");

            entity.HasOne(d => d.Tipo).WithMany(p => p.Contribuyentes)
                .HasForeignKey(d => d.TipoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Contribuyentes_Tipo");
        });

        modelBuilder.Entity<Estado>(entity =>
        {
            entity.ToTable("ESTADO");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("descripcion");
        });

        modelBuilder.Entity<Tipo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Nombre__3214EC27A37E0E89");

            entity.ToTable("TIPO");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.Descripción)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}