// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorApp2.Models;

public partial class Tipo
{
    public int Id { get; set; }

    public string Descripción { get; set; }

    public virtual ICollection<Contribuyente> Contribuyentes { get; set; } = new List<Contribuyente>();
}