// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using BlazorApp2.Entities;  
using Microsoft.EntityFrameworkCore;

namespace BlazorApp2;

public partial class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Contribuyente> Contribuyentes { get; set; }

    public virtual DbSet<Tipo> Tipos { get; set; }
    public virtual DbSet<Estatus> Estatuses { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        //modelbuilder.entity<contribuyente>(entity =>
        //{
        //    entity.haskey(e => e.id).hasname("pk__contribu__3213e83f86178b7e");

        //    entity.totable("contribuyente");

        //    entity.property(e => e.id)
        //        .valuegeneratednever()
        //        .hascolumnname("id");
        //    entity.property(e => e.nombre)
        //        .isrequired()
        //        .hasmaxlength(100)
        //        .isunicode(false)
        //        .hascolumnname("nombre");
        //    entity.property(e => e.tipoid).hascolumnname("tipo_id");
        //});

        //modelbuilder.entity<tipo>(entity =>
        //{
        //    entity.haskey(e => e.id).hasname("pk__tipo__3213e83fbb25880c");

        //    entity.totable("tipo");

        //    entity.property(e => e.id)
        //        .valuegeneratednever()
        //        .hascolumnname("id");
        //    entity.property(e => e.nombre)
        //        .isrequired()
        //        .hasmaxlength(100)
        //        .isunicode(false)
        //        .hascolumnname("nombre");
        //});

        //OnModelCreatingPartial(modelbuilder);
    }

    //partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}